logging:
  file: ./logs/app.log
  level: INFO
scheduling:
  frequency: once
  time: 09:00
sources:
  cnbc:
    categories:
    - markets
    - business
    - investing
    enabled: true
    max_articles: 50
  cointelegraph:
    cryptocurrencies:
    - BTC
    - ETH
    - XRP
    - ADA
    enabled: true
    include_news: true
  yahoo_finance:
    data_points:
    - price
    - volume
    - market_cap
    - pe_ratio
    enabled: true
    symbols:
    - AAPL
    - MSFT
    - GOOGL
    - AMZN
storage:
  path: ./data
  type: csv
